# Generated by Django 5.2 on 2025-05-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_login_google",
            field=models.BooleanField(default=False),
        ),
    ]
